[target.thumbv7em-none-eabi]
runner = "probe-run --chip nRF52840_xxAA"
rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=--nmagic",
]

[build]
target = "thumbv7em-none-eabi"

[alias]
rb = "run --bin light_controller"
rrb = "run --release --bin light_controller"
